rango/urls.py
from django.urls import path

from rango import views


app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import rango.urls
import rango.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', rango.views.index, name='index'),
    path('rango/', include(rango.urls)),
]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

rango/models.py
from django.db import models


# Create your models here.
from django.template.defaultfilters import slugify


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from rango.models import Page, Category


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.urls import reverse

from rango.forms import CategoryForm, PageForm
from rango.models import Category, Page


def index(request: HttpRequest) -> HttpResponse:
    context_dict = {'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!'}

    context_dict['categories'] = Category.objects.order_by('-likes')[:5]
    context_dict['pages'] = Page.objects.order_by('-views')[:5]

    return render(request, 'rango/index.html', context=context_dict)


def about(request: HttpRequest) -> HttpResponse:
    return render(request, 'rango/about.html')


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)


def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect('/rango/')
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',
                kwargs={'category_name_slug':
                category_name_slug}))
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        here is the about page.
        <strong>This tutorial has been put together by me</strong>
    </div>
    <div>
        <a href="/rango/">Index</a><br/>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango"/>
        <br>
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat"/>
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}


{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="/rango/add_category/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category"/>
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}


{% block body_block %}
    <h1>Add a Page</h1>
    <div>
        <form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Page"/>
        </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>

<body>
<div>
    {% block body_block %}
    {% endblock %}
</div>
<div>
    {% block sidebar %}
        {% get_category_list %}
    {% endblock %}
</div>

<hr />
<div>
    <ul>
        <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
    </ul>
</div>
</body>

</html>

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br/>
    {% else %}
        The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        hey there partner! <br/>
        <strong>{{ boldmessage }}</strong><br/>
    </div>
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango">
    </div>

    <div>
        <h2>Most Liked Categories</h2>
        {% if categories %}
            {% for category in categories %}
                <li><a href="/rango/category/{{ category.slug }}">{{ category.name }}</a></li>
            {% endfor %}
        {% else %}
            <strong>There are no pages present.</strong>
        {% endif %}
    </div>

    <div>
        <h2>Most Viewed Pages</h2>
        {% if pages %}
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    </div>

{% endblock %}